/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.JTable;
import javax.swing.*;
import javax.swing.table.TableModel;

//import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableModel;
/**
 *
 * @author kamlesh
 */
public class AddBooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBooking
     *
     * @param loginuser
     */
    String luser;

    public AddBooking(String loginuser) {
        initComponents();
        busSourceCBFillData();
        busDestinationCBFillData();
        this.luser = loginuser;
        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        jDateChooser2.setDateFormatString("yyyy/MM/dd");
    }

    public void busSourceCBFillData() {
//        try {
//            Class.forName("oracle.jdbc.driver.OracleDriver");
//            String databaseURL = "jdbc:oracle:thin:@localhost:1521:ORCL";
//            Connection con = DriverManager.getConnection(databaseURL, "system", "LOkesh+93");
//            Statement stat = con.createStatement();
//            String selectQuery = "select distinct(bus_source) from bus_details";
//            ResultSet rs = stat.executeQuery(selectQuery);
//            while (rs.next()) {
//                sourceCB.addItem(rs.getString("bus_source"));
//
//            }
//
//        } catch (ClassNotFoundException | SQLException e) {
//            System.out.println(e);
//        }
 try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String databaseURL = "jdbc:oracle:thin:@localhost:1521:ORCL";
        Connection con = DriverManager.getConnection(databaseURL, "system", "LOkesh+93");
        Statement stat = con.createStatement();
        String selectQuery = "select distinct(bus_source) from bus_details";
        ResultSet rs = stat.executeQuery(selectQuery);
        while (rs.next()) {
            sourceCB.addItem(rs.getString("bus_source"));
        }
        con.close(); // Close the connection when done
    } catch (ClassNotFoundException | SQLException e) {
        // Print stack trace for debugging purposes
        e.printStackTrace();
        // Or print the exception message to identify the specific error
        System.out.println("Error: " + e.getMessage());
    }
    }

    public void busDestinationCBFillData() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String databaseURL = "jdbc:oracle:thin:@localhost:1521:ORCL";
            Connection con = DriverManager.getConnection(databaseURL, "system", "LOkesh+93");
            Statement stat = con.createStatement();
            String selectQuery = "select distinct(bus_dest) as bus_dest  from bus_details";
            ResultSet rs = stat.executeQuery(selectQuery);
            while (rs.next()) {
                destinationCB.addItem(rs.getString("bus_dest"));

            }

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sourceCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        destinationCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Source");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 50, -1, -1));

        sourceCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(sourceCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 47, 94, -1));

        jLabel2.setText("Destination");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 50, -1, -1));

        getContentPane().add(destinationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 47, 95, -1));

        jLabel3.setText("Starting From");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 91, -1, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "bus_ o", "movement", "bus_source", "bus_dest", "depart_date", "depart_time", "price", "total_seat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 670, 170));

        jLabel4.setText("Search Result.........");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 168, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Add Booking Info");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 6, 147, -1));

        jLabel7.setText("Upto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 91, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/management/cool-background (16).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 860, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void infoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String source = (String) sourceCB.getSelectedItem();
        String destination = (String) destinationCB.getSelectedItem();
        java.util.Date departDateD = jDateChooser1.getDate();
        java.sql.Date sqlDate = new java.sql.Date(departDateD.getTime());
        SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String departDate1 = oDateFormat.format(sqlDate);
        departDateD = jDateChooser2.getDate();
        sqlDate = new java.sql.Date(departDateD.getTime());
        String departDate2 = oDateFormat.format(sqlDate);

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String databaseURL = "jdbc:oracle:thin:@localhost:1521:ORCL";
            Connection con = DriverManager.getConnection(databaseURL, "system", "LOkesh+93");
            Statement stat = con.createStatement();
            String selectQuery = "select * from bus_details where bus_source='" + source + "' and bus_dest='" + destination + "'";
            ResultSet rs = stat.executeQuery(selectQuery);

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      
        int index =jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String bus_no=(String) model.getValueAt(index, 1);
        String movement=(String) model.getValueAt(index, 2);
        String bus_source=(String) model.getValueAt(index, 3);
        String bus_dest=(String) model.getValueAt(index, 4);
        String depart_date=model.getValueAt(index, 5).toString();  
        String depart_time=(String) model.getValueAt(index, 6);
        String price=(String) model.getValueAt(index, 7);
        String avail_seat=(String) model.getValueAt(index, 8);
        
        
        BookingFormFrame=new JFrame();
        BookingFormPanel=new JPanel();
        gl=new GridLayout(0,4);
        l1=new JLabel("Bus No");
        l11=new JLabel(bus_no);
        l2=new JLabel("Movement");
        l12=new JLabel(movement);
        l3=new JLabel("Bus Source");
        l13=new JLabel(bus_source);
        l4=new JLabel("Bus Dest");
        l14=new JLabel(bus_dest);
        l5=new JLabel("Depart Date");
        l15=new JLabel(depart_date);
        l6=new JLabel("Depart Time");
        l16=new JLabel(depart_time);
        l7=new JLabel("Price/seat");
        l17=new JLabel(price);
        l8=new JLabel("Available Seat");
        l18=new JLabel(avail_seat);
        seatnoL=new JLabel("Seat No");
        idnoL=new JLabel("ID No.");
        fnameL=new JLabel("First Name");
        lnameL=new JLabel("Last Name");
        t1=new JTextField(20);
        t2=new JTextField(20);
        t3=new JTextField(20);
        t4=new JTextField(20);
        
        BookingFormFrame.getContentPane().add(BookingFormPanel);
        BookingFormPanel.setLayout(gl);
        
        BookingFormPanel.add(l1);
        BookingFormPanel.add(l11);
        BookingFormPanel.add(l2);
        BookingFormPanel.add(l12);
        BookingFormPanel.add(l3);
        BookingFormPanel.add(l13);
        BookingFormPanel.add(l4);
        BookingFormPanel.add(l14);
        BookingFormPanel.add(l5);
        BookingFormPanel.add(l15);
        BookingFormPanel.add(l6);
        BookingFormPanel.add(l16);
        BookingFormPanel.add(l7);
        BookingFormPanel.add(l17);
        BookingFormPanel.add(l8);
        BookingFormPanel.add(l18);
        
        BookingFormPanel.add(seatnoL);
        BookingFormPanel.add(t1);
        BookingFormPanel.add(idnoL);
         BookingFormPanel.add(t2);
        BookingFormPanel.add(fnameL);
         BookingFormPanel.add(t3);
        BookingFormPanel.add(lnameL);
         BookingFormPanel.add(t4);
        
       int result = JOptionPane.showConfirmDialog(BookingFormFrame,BookingFormPanel,"Booking Form",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(result==JOptionPane.OK_OPTION)
        {
            String booking_user=luser;
            String seatno=t1.getText();
            String idno=t2.getText();
            String first_tname=t3.getText();
            String last_name=t4.getText();
            try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String databaseURL = "jdbc:oracle:thin:@localhost:1521:ORCL";
            Connection con = DriverManager.getConnection(databaseURL, "system", "LOkesh+93");
            Statement stat = con.createStatement();    
           if(con==null)
           {
        } else {
               String insertQuery = "insert into bus_booking values(booking_id_seq.NEXTVAL,'" + booking_user + "','" +depart_date  + "','" + bus_no + "','" + seatno + "','" + idno + "','" + first_tname + "','" + last_name + "')";
               
               int i= stat.executeUpdate(insertQuery);
               if(i==1)
               {
                   
                   int remaining_seat=Integer.parseInt(avail_seat)-Integer.parseInt(seatno);
                   
                   String updateQuery="update bus_details set total_seat='"+remaining_seat+"' where bus_no='"+bus_no+"' and movement='"+movement+"' and depart_date='"+depart_date+"'";
                   int j=stat.executeUpdate(updateQuery);
                   if(j==1)
                   {
                       
                       String source=(String)sourceCB.getSelectedItem();
                       String destination=(String)destinationCB.getSelectedItem();
                       java.util.Date fromDate=jDateChooser1.getDate();
                       java.util.Date toDate=jDateChooser2.getDate();
                       
                       SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                       String fromDateFormated=sdf.format(fromDate);
                       String toDateFormated=sdf.format(toDate);
                       infoMessage("Booking Done", "Alert !!");
                       
                       String selectQuery1 = "select * from bus_details where bus_source='"+source+"' and bus_dest='"+destination+"' and depart_date between '"+fromDateFormated+"' and '"+toDateFormated+"'";
                       ResultSet rs1=stat.executeQuery(selectQuery1);
                       
                       jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
                       jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                       
                   }
               }      }
        }
        catch(Exception e)
                {
                    System.out.println(e);
                }
            
        }
     
        
       
             
    }//GEN-LAST:event_jTable1MouseClicked
/**/
    GridLayout gl;
    public JFrame BookingFormFrame;
    public JPanel BookingFormPanel;
    public JLabel l1, l2, l3, l4, l5, l6, l7, l8, l11, l12, l13, l14, l15, l16, l17, l18, seatnoL, idnoL, fnameL, lnameL;
    public JComboBox seatCB;
    public JTextField t1, t2, t3, t4;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destinationCB;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sourceCB;
    // End of variables declaration//GEN-END:variables
}
